#!/bin/bash

. /etc/os-release
CONFIG_DIR=/etc/yum.repos.d
arch=`arch`
releasever=${VERSION_ID}

mkdir -p ${CONFIG_DIR}/old
mv ${CONFIG_DIR}/*.repo ${CONFIG_DIR}/old/ 2>/dev/null

cat <<EOF > base.repo
[base]
name=aliyun base repo
baseurl=https://mirrors.aliyun.com/centos/${releasever}/os/${arch}/
gpgcheck=1
gpgkey=https://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-${releasever}

cat <<EOF > epel.repo
[epel]
name=aliyun epel repo
baseurl=https://mirrors.aliyun.com/epel/${releasever}/${arch}/
gpgcheck=1
gpgkey=https://mirrors.aliyun.com/epel/RPM-GPG-KEY-EPEL-${releasever}

mv {base,epel}.repo ${CONFIG_DIR}/
